services:
  mongodb:
    image: mongo:5
    restart: always
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - POSTGRES:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=main_db
    ports:
     - "27016:27016"


volumes:
  mongodb:
    driver: local
  postgres:
    driver: local
