services:
  mongodb:
    image: mongo:5
    restart: always
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=main_db
    ports:
      - "27016:5432"
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catsdb
    ports:
      - "27015:3306"
    volumes:
      - mysql:/var/lib/mysql


volumes:
  mongodb:
    driver: local
  postgres:
    driver: local
  mysql:
    driver: local
