services:
  s3mock:
    image: adobe/s3mock:3.5.2
    environment:
      - initialBuckets=bucket
    ports:
      - "9090:9090"
  mongodb:
    image: mongo:5
    restart: always
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=main_db
    ports:
      - "27016:5432"
  mysql:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: catsdb
    ports:
      - "27015:3306"
    volumes:
      - mysql:/var/lib/mysql
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: mypassword
      MARIADB_DATABASE: catsdb
    ports:
      - "27018:3306"
    volumes:
      - mariadb:/var/lib/mysql
  clickhouse:
    image: clickhouse/clickhouse-server:24
    environment:
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_DB=main_db
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "27019:8123"
    volumes:
      - clickhouse:/var/lib/clickhouse
  mongodb-replica:
    image: bitnami/mongodb:4.4 # Newer versions do not run on Apple Silicon
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=password
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - "27020:27017"
    volumes:
      - "mongodb-replica:/bitnami/mongodb"
  server:
    build:
      context: ../end2end/server
    ports:
      - "5874:3000"
  libsql:
    image: ghcr.io/tursodatabase/libsql-server:v0.24.30
    platform: linux/amd64
    ports:
      - "27021:8080"
    volumes:
      - libsql:/var/lib/sqld

volumes:
  mongodb:
    driver: local
  postgres:
    driver: local
  mysql:
    driver: local
  mariadb:
    driver: local
  clickhouse:
    driver: local
  mongodb-replica:
    driver: local
