services:
  s3mock:
    image: adobe/s3mock:3.5.2
    environment:
      - initialBuckets=bucket
    ports:
      - "9090:9090"
  mongodb:
    image: mongo:5
    restart: always
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=main_db
    ports:
      - "27016:5432"
  mysql:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: catsdb
    ports:
      - "27015:3306"
    volumes:
      - mysql:/var/lib/mysql
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"  # HTTP interface
    volumes:
      - clickhouse:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=main_db
      - CLICKHOUSE_USER=root
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1

volumes:
  mongodb:
    driver: local
  postgres:
    driver: local
  mysql:
    driver: local
  clickhouse:
    driver: local
