service: lambda-mongodb
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x

functions:
  login:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: post
