import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script
        id="tailwindcss"
        src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"
        strategy="afterInteractive"  
      />
      <body className={`${inter.className} dark bg-black text-white font-sans antialiased`}>{children}</body>
    </html>
  );
}
