name: Lint code and run tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5
        env:
          "MONGO_INITDB_ROOT_USERNAME": "root"
          "MONGO_INITDB_ROOT_PASSWORD": "password"
        ports:
          - 27017:27017
      postgres:
        image: postgres:14-alpine
        env:
          "POSTGRES_PASSWORD": "password"
          "POSTGRES_USER": "root"
          "POSTGRES_DB": "main_db"
        ports:
          - "27016:5432"
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          "ACCEPT_EULA": "Y"
          "MSSQL_SA_PASSWORD": "Strongeeeee%Password"
          "MSSQL_PID": "Developer"
        ports:
          - "27014:1433"
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: make install
      - run: make lint
      - run: make test-ci
      - name: "Upload coverage"
        uses: codecov/codecov-action@v4.0.1
        with:
          file: ./library/.tap/converage/report/lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          slug: AikidoSec/guard-node
