name: Unit tests Windows
on:
  push: {}
  workflow_call: {}
jobs:
  test-windows:
    runs-on: windows-latest
    services:
      s3:
        image: adobe/s3mock
        env:
          "initialBuckets": "bucket"
        ports:
          - "9090:9090"
      mongodb:
        image: mongo:5
        env:
          "MONGO_INITDB_ROOT_USERNAME": "root"
          "MONGO_INITDB_ROOT_PASSWORD": "password"
        ports:
          - 27017:27017
      postgres:
        image: postgres:14-alpine
        env:
          "POSTGRES_PASSWORD": "password"
          "POSTGRES_USER": "root"
          "POSTGRES_DB": "main_db"
        ports:
          - "27016:5432"
      mysql:
        image: mysql:8.0
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # We need to use this long command in order to execute the last part : mysql_native_password
        # https://stackoverflow.com/questions/60902904/how-to-pass-mysql-native-password-to-mysql-service-in-github-actions
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5 -e MYSQL_ROOT_PASSWORD=mypassword -e MYSQL_DATABASE=catsdb --entrypoint sh mysql:8.0 -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
        ports:
          - "27015:3306"
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Add local.aikido.io to hosts file
        run: |
          Add-Content -Path "C:\Windows\System32\drivers\etc\hosts" -Value "127.0.0.1 local.aikido.io"
      - run: npm install
      - run: npm run test:ci
      - name: "Upload coverage"
        uses: codecov/codecov-action@v4.0.1
        with:
          file: ./library/.tap/report/lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          slug: AikidoSec/firewall-node
