name: Unit tests (ESM)
on:
  push: {}
  workflow_call: {}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Add local.aikido.io to /etc/hosts
        run: |
          sudo echo "127.0.0.1 local.aikido.io" | sudo tee -a /etc/hosts
      - run: make install
      - run: cd library && npm run test:esm
      - name: "Upload coverage"
        uses: codecov/codecov-action@v4.0.1
        with:
          file: ./library/.tap/report/lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          slug: AikidoSec/firewall-node
